version: '3'

services:
  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=inmobiliaria
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5555:5432"

  client:
    image: 'dpage/pgadmin4'
    container_name: client
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    ports:
      - "5050:80"

  api:
    image: inmoboscoapi:1.0
    container_name: backend
    ports:
      - 8080:8080
    depends_on: 
      - db
      - client
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/inmobiliaria
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user

  frontend:
    image: inmoboscoapifront:1.0
    container_name: angular
    ports:
      - 80:80
    depends_on:
      - api
